name: KochiAnvils
version: 1.0
main: net.punchpvp.kochianvils.kochiAnvils
commands:
  kochiAnvil:
    description: Comando para activar/desactivar yunques irrompibles y recargar configuración.
    usage: /<command> <toggle|reload>
    aliases: [ka]